version: '2'
services:
    consul:
        image: qnib/consul
        networks: 
         - global
        hostname: consul
        container_name: consul
        environment:
         - DC_NAME=dc1
         - COLLECT_METRICS=false
         - RUN_SERVER=true
         - CONSUL_BOOTSTRAP_EXPECT=1
         - constraint:node==venus001
        ports:
         - 18500:8500

networks:
  global:
    external: true
