hpcg:
    image: ${IMAGE}
    hostname: hpcg${CNT}
    container_name: hpcg${CNT}
    net: global
    volumes:
     - /chome/:/chome/
     - /scratch/:/scratch/
    dns: 127.0.0.1
    privileged: true
    devices:
     - "/dev/infiniband/uverbs0:/dev/infiniband/uverbs0"
     - "/dev/infiniband/rdma_cm:/dev/infiniband/rdma_cm"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      memlock:
        soft: 68719476736
        hard: 68719476736
    environment:
     - DC_NAME=dc1
     - RUN_SERVER=false
     - CONSUL_CLUSTER_IPS=consul
     - COLLECT_METRICS=true
     - SUPERVISOR_SKIP_SRV=sensu-api,sensu-server
     - SENSU_CLIENT=true
     - SENSU_FORCE_CLIENT=true
     - SENSU_RABBITMQ_HOST=${SENSU_RABBITMQ_HOST}
     - SENSU_RABBITMQ_PASSWD=${SENSU_RABBITMQ_HOST}
     - constraint:node==venus00${CNT}
