version: '2'
services:
  hpcg1:
    image: ${IMAGE}
    volumes:
     - /chome/:/chome/
     - /scratch/:/scratch/
    dns: 127.0.0.1
    privileged: true
    devices:
     - "/dev/infiniband/uverbs0:/dev/infiniband/uverbs0"
     - "/dev/infiniband/rdma_cm:/dev/infiniband/rdma_cm"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
      memlock:
        soft: 68719476736
        hard: 68719476736
    environment:
     - DC_NAME=dc1
     - RUN_SERVER=false
     - CONSUL_CLUSTER_IPS=consul
    networks:
     - global
    hostname: hpcg1
    container_name: hpcg1
    environment:
     - constraint:node==venus001

networks:
  global:
    external: true
