consul1:
    extends:
      file: base.yml
      service: consul
    hostname: consul1
    container_name: consul1
    environment:
     - constraint:node==venus001
    ports:
     - "28501:8500"

consul2:
    extends:
      file: base.yml
      service: consul
    hostname: consul2
    container_name: consul2
    environment:
     - constraint:node==venus002
    ports:
     - "28502:8500"

consul8:
    extends:
      file: base.yml
      service: consul
    hostname: consul8
    container_name: consul8
    environment:
     - constraint:node==venus008
    ports:
     - "28508:8500"

zk1:
    extends:
      file: base.yml
      service: zookeeper
    hostname: zk1
    container_name: zk1
    environment:
     - MYID=1
     - constraint:node==venus001

zk2:
    extends:
      file: base.yml
      service: zookeeper
    hostname: zk2
    container_name: zk2
    environment:
     - MYID=2
     - constraint:node==venus002

zk3:
    extends:
      file: base.yml
      service: zookeeper
    hostname: zk3
    container_name: zk3
    environment:
     - MYID=3
     - constraint:node==venus003

zk4:
    extends:
      file: base.yml
      service: zookeeper
    hostname: zk4
    container_name: zk4
    environment:
     - MYID=4
     - constraint:node==venus004

zkui:
    extends:
      file: base.yml
      service: base
    hostname: zkui
    container_name: zkui
    image: 192.168.12.11:5000/qnib/zkui
    environment:
     - constraint:node==venus008
    ports:
    - 9090:9090

kafka1:
    extends:
      file: base.yml
      service: kafka
    environment:
     - constraint:node==venus001
     #- BARE_HOST=kafka1
    hostname: kafka1
    container_name: kafka1

kafka2:
    extends:
      file: base.yml
      service: kafka
    environment:
     - constraint:node==venus002
    hostname: kafka2
    container_name: kafka2

kafka4:
    extends:
      file: base.yml
      service: kafka
    environment:
     - constraint:node==venus004
     - BARE_HOST=kafka1
    hostname: kafka4
    container_name: kafka4

kafka-manager:
    extends:
      file: base.yml
      service: base
    image: 192.168.12.11:5000/qnib/kafka-manager
    hostname: kafka-manager
    container_name: kafka-manager
    environment:
     - constraint:node==venus008
     - APPLICATION_SECRET=letmein
    ports:
    - 9000:9000
    volumes:
    - ./conf/:/kafka-manager-1.2.7/conf/

kafka-monitor:
    extends:
      file: base.yml
      service: base
    image: 192.168.12.11:5000/qnib/kafka-monitor
    hostname: kafka-monitor
    container_name: kafka-monitor
    environment:
     - constraint:node==venus008
    ports:
    - 8080:8080

samza1:
    extends:
      file: base.yml
      service: samza
    hostname: samza1
    container_name: samza1
    environment:
     - constraint:node==venus001

samza3:
    extends:
      file: base.yml
      service: samza
    hostname: samza3
    container_name: samza3
    environment:
     - constraint:node==venus003

samza5:
    extends:
      file: base.yml
      service: samza
    hostname: samza5
    container_name: samza5
    environment:
     - constraint:node==venus005

samza6:
    extends:
      file: base.yml
      service: samza
    hostname: samza6
    container_name: samza6
    environment:
     - constraint:node==venus006
